### ISSUE TITLE
Dataadapter crash

### ISSUE THREAD

**Issue by MaherBTA** [WedjaaOpen/ElasticJasper#5]
Hi,
I am  trying to use ElasticJasper adapter on jasper studio.
when i create a new report using Elasticjasper adapter i get this error:

**java.lang.NoSuchMethodError: net.sf.jasperreports.data.AbstractDataAdapterService: method ()V not found
at net.wedjaa.jasper.elasticsearch.adapter.ESAdapterService.(ESAdapterService.java:51)
at net.wedjaa.jasper.elasticsearch.adapter.ESAdapterFactory.createDataAdapterService(ESAdapterFactory.java:111)
at net.wedjaa.jasper.elasticsearch.adapter.ESAdapterFactory.createDataAdapterService(ESAdapterFactory.java:119)
at com.jaspersoft.studio.data.DataAdapterServiceFactoryImpl.getDataAdapterService(DataAdapterServiceFactoryImpl.java:46)
at net.sf.jasperreports.data.DataAdapterServiceUtil.getService(DataAdapterServiceUtil.java:71)
at com.jaspersoft.studio.data.ui.SimpleQueryWizardDataEditorComposite.readFields(SimpleQueryWizardDataEditorComposite.java:218)
at com.jaspersoft.studio.wizards.datasource.StaticWizardDataSourcePage.run(StaticWizardDataSourcePage.java:380)**

Note that I am using elasticsearch 2.3.0 and jasper studio the 6.2.2

Thank you in advance

**Comment by Wedjaa** [comment]
What version of the plugin are you using?

**Comment by MaherBTA** [comment]
I installed the plugin using the install new software: 

https://github.com/WedjaaOpen/ElasticJasperSite/raw/master/

**Comment by jmccollom** [comment]
I saw this as well.  This happens with Jaspersoft Studio version 6.2.2.  I was able to get it to work with version 6.2.0.

**Comment by Wedjaa** [comment]
I will look into what changed in Jaspersoft Studio and see if I can repro.

**Comment by Wedjaa** [comment]
Fixed with latest release of the plugin.

**Comment by jmccollom** [comment]
Cool, thanks!

**Comment by cjschmitz** [comment]
I understand this issue is closed, but I was just curious if there are plans to update the plugin to support version 2.3.  If so, when might it be expected?
